# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mp3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mp3.proto',
  package='mp3',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tmp3.proto\x12\x03mp3\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0c\x62\x65ginMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1b\n\nbeginReply\x12\r\n\x05value\x18\x01 \x01(\t\"\x19\n\ngetMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x19\n\x08getReply\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nsetMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x17\n\x08setReply\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\rcommitMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0b\x63ommitReply\x12\r\n\x05value\x18\x01 \x01(\t2\xaf\x02\n\x07Greeter\x12\x30\n\x08SayHello\x12\x11.mp3.HelloRequest\x1a\x0f.mp3.HelloReply\"\x00\x12\x35\n\rSayHelloAgain\x12\x11.mp3.HelloRequest\x1a\x0f.mp3.HelloReply\"\x00\x12-\n\x05\x62\x65gin\x12\x11.mp3.beginMessage\x1a\x0f.mp3.beginReply\"\x00\x12,\n\x08getValue\x12\x0f.mp3.getMessage\x1a\r.mp3.getReply\"\x00\x12,\n\x08setValue\x12\x0f.mp3.setMessage\x1a\r.mp3.setReply\"\x00\x12\x30\n\x06\x63ommit\x12\x12.mp3.commitMessage\x1a\x10.mp3.commitReply\"\x00\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='mp3.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mp3.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=46,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='mp3.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='mp3.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=77,
)


_BEGINMESSAGE = _descriptor.Descriptor(
  name='beginMessage',
  full_name='mp3.beginMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mp3.beginMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=106,
)


_BEGINREPLY = _descriptor.Descriptor(
  name='beginReply',
  full_name='mp3.beginReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mp3.beginReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=135,
)


_GETMESSAGE = _descriptor.Descriptor(
  name='getMessage',
  full_name='mp3.getMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mp3.getMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=162,
)


_GETREPLY = _descriptor.Descriptor(
  name='getReply',
  full_name='mp3.getReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mp3.getReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=189,
)


_SETMESSAGE = _descriptor.Descriptor(
  name='setMessage',
  full_name='mp3.setMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mp3.setMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mp3.setMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=231,
)


_SETREPLY = _descriptor.Descriptor(
  name='setReply',
  full_name='mp3.setReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mp3.setReply.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=256,
)


_COMMITMESSAGE = _descriptor.Descriptor(
  name='commitMessage',
  full_name='mp3.commitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mp3.commitMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=286,
)


_COMMITREPLY = _descriptor.Descriptor(
  name='commitReply',
  full_name='mp3.commitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mp3.commitReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['beginMessage'] = _BEGINMESSAGE
DESCRIPTOR.message_types_by_name['beginReply'] = _BEGINREPLY
DESCRIPTOR.message_types_by_name['getMessage'] = _GETMESSAGE
DESCRIPTOR.message_types_by_name['getReply'] = _GETREPLY
DESCRIPTOR.message_types_by_name['setMessage'] = _SETMESSAGE
DESCRIPTOR.message_types_by_name['setReply'] = _SETREPLY
DESCRIPTOR.message_types_by_name['commitMessage'] = _COMMITMESSAGE
DESCRIPTOR.message_types_by_name['commitReply'] = _COMMITREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

beginMessage = _reflection.GeneratedProtocolMessageType('beginMessage', (_message.Message,), dict(
  DESCRIPTOR = _BEGINMESSAGE,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.beginMessage)
  ))
_sym_db.RegisterMessage(beginMessage)

beginReply = _reflection.GeneratedProtocolMessageType('beginReply', (_message.Message,), dict(
  DESCRIPTOR = _BEGINREPLY,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.beginReply)
  ))
_sym_db.RegisterMessage(beginReply)

getMessage = _reflection.GeneratedProtocolMessageType('getMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGE,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.getMessage)
  ))
_sym_db.RegisterMessage(getMessage)

getReply = _reflection.GeneratedProtocolMessageType('getReply', (_message.Message,), dict(
  DESCRIPTOR = _GETREPLY,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.getReply)
  ))
_sym_db.RegisterMessage(getReply)

setMessage = _reflection.GeneratedProtocolMessageType('setMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETMESSAGE,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.setMessage)
  ))
_sym_db.RegisterMessage(setMessage)

setReply = _reflection.GeneratedProtocolMessageType('setReply', (_message.Message,), dict(
  DESCRIPTOR = _SETREPLY,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.setReply)
  ))
_sym_db.RegisterMessage(setReply)

commitMessage = _reflection.GeneratedProtocolMessageType('commitMessage', (_message.Message,), dict(
  DESCRIPTOR = _COMMITMESSAGE,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.commitMessage)
  ))
_sym_db.RegisterMessage(commitMessage)

commitReply = _reflection.GeneratedProtocolMessageType('commitReply', (_message.Message,), dict(
  DESCRIPTOR = _COMMITREPLY,
  __module__ = 'mp3_pb2'
  # @@protoc_insertion_point(class_scope:mp3.commitReply)
  ))
_sym_db.RegisterMessage(commitReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='mp3.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=319,
  serialized_end=622,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='mp3.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='mp3.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='begin',
    full_name='mp3.Greeter.begin',
    index=2,
    containing_service=None,
    input_type=_BEGINMESSAGE,
    output_type=_BEGINREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getValue',
    full_name='mp3.Greeter.getValue',
    index=3,
    containing_service=None,
    input_type=_GETMESSAGE,
    output_type=_GETREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setValue',
    full_name='mp3.Greeter.setValue',
    index=4,
    containing_service=None,
    input_type=_SETMESSAGE,
    output_type=_SETREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='commit',
    full_name='mp3.Greeter.commit',
    index=5,
    containing_service=None,
    input_type=_COMMITMESSAGE,
    output_type=_COMMITREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
